# Exploring Denver crime data

In [1]:
import pandas as pd
import numpy as np

In [2]:
#read csv for teh crimes

df = pd.read_csv('crime2021.csv')
df.head()

,incident_id,offense_id,offense_code,offense_code_extension,offense_type_id,offense_category_id,first_occurrence_date,last_occurrence_date,reported_date,incident_address,geo_x,geo_y,geo_lon,geo_lat,district_id,precinct_id,neighborhood_id,is_crime,is_traffic,victim_count
0,2021387586,2021387586299900,2999,0,criminal-mischief-other,public-disorder,7/7/2021 9:02:00 PM,NaN,7/8/2021 12:55:00 AM,815 16TH ST,3142470.0,1697098.0,-104.993342,39.746248,6,611,cbd,1,0,1
1,2021415767,2021415767299900,2999,0,criminal-mischief-other,public-disorder,7/21/2021 4:41:00 PM,NaN,7/21/2021 4:41:00 PM,5TH ST / W COLFAX AVE,3138188.0,1694755.0,-105.008615,39.739881,1,123,lincoln-park,1,0,1
2,20216014714,20216014714299900,2999,0,criminal-mischief-other,public-disorder,7/13/2021 6:30:00 AM,7/13/2021 8:00:00 AM,7/13/2021 8:53:00 AM,1649 N DOWNING ST,3147971.0,1695800.0,-104.973806,39.742599,6,621,north-capitol-hill,1,0,1
3,2021321536,2021321536299900,2999,0,criminal-mischief-other,public-disorder,6/6/2021 11:45:00 PM,NaN,6/7/2021 1:12:00 AM,1800 LARIMER ST,3142075.0,1698868.0,-104.994712,39.751113,6,612,union-station,1,0,1
4,2021387948,2021387948299900,2999,0,criminal-mischief-other,public-disorder,7/8/2021 12:00:00 AM,7/8/2021 12:54:00 AM,7/8/2021 1:57:00 AM,2449 W DUNKELD PL,3135673.0,1701938.0,-105.017422,39.759636,1,113,highland,1,0,1

In [3]:
df.shape

(72954, 20)

In [7]:
print(df['reported_date'].max(),df['reported_date'].min())

9/9/2022 3:00:00 PM 1/1/2021 10:01:00 PM

In [8]:
#read offense codes
cd = pd.read_csv('offense_codes.csv')
cd.head()

,OBJECTID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_TYPE_NAME,OFFENSE_CATEGORY_ID,OFFENSE_CATEGORY_NAME,IS_CRIME,IS_TRAFFIC
0,1,2804,1,stolen-property-possession,Possession of stolen property,all-other-crimes,All Other Crimes,1,0
1,2,2804,2,fraud-possess-financial-device,Possession of a financial device,all-other-crimes,All Other Crimes,1,0
2,3,2901,0,damaged-prop-bus,Damaged business property,public-disorder,Public Disorder,1,0
3,4,2902,0,criminal-mischief-private,Criminal mischief to private property,public-disorder,Public Disorder,1,0
4,5,2903,0,criminal-mischief-public,Criminal mischief to public property,public-disorder,Public Disorder,1,0

In [9]:
df['offense_code'].value_counts()

2404    12399
2999     9094
2305     7782
2399     6261
2304     5817
        ...
3501        1
5011        1
907         1
5302        1
3582        1
Name: offense_code, Length: 128, dtype: int64

In [10]:
cd[cd['OFFENSE_CODE'] == 2404]

,OBJECTID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_TYPE_NAME,OFFENSE_CATEGORY_ID,OFFENSE_CATEGORY_NAME,IS_CRIME,IS_TRAFFIC
261,262,2404,0,theft-of-motor-vehicle,Motor vehicle theft,auto-theft,Auto Theft,1,0